Repository global-platform/selfservice-bootstrap, pull requests merged in 2021-08, with the labels that each got.

#27 chore(deps): update terraform github.com/global-devops-terraform/jenkins-roles to v1.14.1
  main.tf
Labels: size/XS, ✅ Approved

#28 feat: Sync
  .github/CODEOWNERS
  .github/DESCRIPTION.md
  .gitignore
  Jenkinsfile
  README.md
  main.tf
  terraform.tf
  variables.tf
Labels: ✅ Approved, size/M

#29 chore(deps): update terraform github.com/global-devops-terraform/jenkins-roles to v1.14.2
  main.tf
Labels: ✅ Approved, size/XS

#30 chore(deps): update terraform github.com/global-devops-terraform/jenkins-roles to v1.15.0
  main.tf
Labels: ✅ Approved, size/XS

#31 chore(deps): update terraform aws to v3.54.0
  terraform.tf
Labels: ✅ Approved, size/XS

#32 chore(deps): update terraform github.com/global-devops-terraform/jenkins-roles to v1.16.0
  main.tf
Labels: ✅ Approved, size/XS

#33 chore(deps): update terraform aws to v3.55.0
  terraform.tf
Labels: ✅ Approved, size/XS

#34 fix: Tidy
  .gitignore
Labels: 🔍 Ready for Review, size/XS
